"""empty message

Revision ID: 070792ea55b4
Revises: 3cbcd9d2f149
Create Date: 2020-12-01 15:03:03.383903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070792ea55b4'
down_revision = '3cbcd9d2f149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
