"""empty message

Revision ID: 3cbcd9d2f149
Revises: d21af5207f0f
Create Date: 2020-11-27 10:04:46.763830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbcd9d2f149'
down_revision = 'd21af5207f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacao', type_='foreignkey')
    op.drop_column('transacao', 'conta_id')
    # ### end Alembic commands ###
