"""empty message

Revision ID: a888e75103b5
Revises: c7cbc71fd5af
Create Date: 2021-02-17 15:33:53.354700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a888e75103b5'
down_revision = 'c7cbc71fd5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta', sa.Column('titulo', sa.String(length=50), nullable=False))
    op.drop_column('conta', 'nome')
    op.drop_column('conta', 'descricao')
    op.add_column('transacao', sa.Column('data', sa.Date(), nullable=False))
    op.add_column('transacao', sa.Column('titulo', sa.String(length=50), nullable=False))
    op.drop_column('transacao', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('nome', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('transacao', 'titulo')
    op.drop_column('transacao', 'data')
    op.add_column('conta', sa.Column('descricao', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('conta', sa.Column('nome', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('conta', 'titulo')
    # ### end Alembic commands ###
